# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='in_print',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='published_date',
            field=models.DateField(verbose_name='%m/%d/%Y'),
        ),
    ]
